LICENSE

LICENSE add @brodybits

---

package.json

in `package.json`
resolves #12
thanks to @zfoltin (Zeno Foltin) for pointing it out

add normalized-options.js to files entry

---

README.md
command.js
lib.js
package.json
templates/android.js
templates/example.js
templates/general.js
templates/ios.js
yarn.lock

based on DRAFT PR #30:
- changes from @timojaask fork, with some additional cleanup & documentation (resolves #22)
- update-notifier@3 update in package dependencies
- new exampleReactNativeVersion option
- some other updates & fixes
TODO items not included in this PR:
- Gradle updates as proposed by @SaeedZhiany in PR #24
- resolve known issues #28 & #29 with React Native 0.60
- document document state of RN 0.60 support (#25)
- document state of Windows support (see #23)

0.6.0 updates part 1

---

templates/android.js

By these changes, developer's library can read android plugin version and react-native version of root project

Gradle updates in android.js

---

package.json
yarn.lock

in `package.json`:
- remove `shelljs` from `devDependencies`
- remove `rnpm` entry

cleanup: remove package items not needed

---

package.json

which was accidentally removed in dbd07a9 (PR #33)
resolves #47

Add cli.js back to files list in package.json

---

.travis.yml

as described in:
* https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
(default configuration for Node.js)

Add .travis.yml for Node.js 8, 10, and 12

---

package.json
yarn.lock

* `eslint@^6.1.0`
* `eslint-plugin-import@^2.18.2`

eslint@6.1 updates in devDependencies

---

tests/lib-android-config-options/__snapshots__/lib-android-config-options.test.js.snap
tests/lib-android-config-options/lib-android-config-options.test.js
tests/lib-example-config-options/__snapshots__/lib-example-config-options.test.js.snap
tests/lib-example-config-options/lib-example-config-options.test.js
tests/lib-ios-config-options/__snapshots__/lib-ios-config-options.test.js.snap
tests/lib-ios-config-options/lib-ios-config-options.test.js
tests/lib-view-android-config-options/__snapshots__/lib-view-android-config-options.test.js.snap
tests/lib-view-android-config-options/lib-view-android-config-options.test.js
tests/lib-view-defaults/__snapshots__/lib-view-defaults.test.js.snap
tests/lib-view-defaults/lib-view-defaults.test.js
tests/lib-view-ios-config-options/__snapshots__/lib-view-ios-config-options.test.js.snap
tests/lib-view-ios-config-options/lib-view-ios-config-options.test.js
tests/lib-view-with-example-config-options/__snapshots__/lib-view-with-example-config-options.test.js.snap
tests/lib-view-with-example-config-options/lib-view-with-example-config-options.test.js
tests/lib-view-with-example-defaults/__snapshots__/lib-view-with-example-defaults.test.js.snap
tests/lib-view-with-example-defaults/lib-view-with-example-defaults.test.js

- testing of the lib API with `view: true`, which was forgotten before
- rename test in `tests/lib-example-options` to `tests/lib-example-config-options` and add some config options to that test
- rename & update a couple more lib API tests that were added before

General test updates

---

tests/lib-cli-command/lib-cli-command-func-android-ios-config-options/__snapshots__/lib-cli-command-func-android-ios-config-options.test.js.snap
tests/lib-cli-command/lib-cli-command-func-android-ios-config-options/lib-cli-command-func-android-ios-config-options.test.js
tests/lib-cli-command/object/__snapshots__/lib-cli-command-object-text.test.js.snap
tests/lib-cli-command/object/lib-cli-command-object-text.test.js

- check values of the object exported by `lib/cli-command.js`
- check the results of running the CLI command `func` function with some options using mocked `fs` I/O object, using a delay timer to wait for the output to finish

cli-command module tests

---

tests/lib-windows-config-options/__snapshots__/lib-windows-config-options.test.js.snap
tests/lib-windows-config-options/lib-windows-config-options.test.js

using a Jest mock to keep using the same uuid in the snapshot
with custom namespace

Windows unit test with config options

---

lib/normalized-options.js

discovered thanks to mutation testing using Stryker

remove code not needed from lib/normalized-options.js

---

README.md

for the following platforms
- tvOS (see #95 - followup work needed)
- Windows - see the following issues:
- #23 - Windows platform support is not stable
- #43 - may be removed due to lack of stability, apparent lack of community interest, and apparent lack of commercial interest
- macOS - under future consideration (#94)
/cc @dlowder-salesforce

document status of out-of-tree platform support

---

lib/lib.js
tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap
tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

which was introduced in: 13f9188b4c6536d9bfda461895b23b2baba4a3bf

remove duplicate `authorEmail` entry from logging

---

.travis.yml

Travis CI matrix, with macOS added

---

README.md

Co-authored-by: Christopher J. Brody <chris@brody.consulting>
Co-authored-by: Johannes Stein <johannesstein@freeze-dev.com>

License section back at the bottom (now as a link)

---

README.md

towards open-source sustainability

[...] add support options with commercial support option

---

templates/android.js
tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap
tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap
tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap
tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap
tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap
tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap
tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap
tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

(with update snapshots in tests)
splitting this out from PR #135 (contributed by @friederbluemle)

no sudo in generated doc for Android

---

templates/android.js
tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap
tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap
tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap
tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap
tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap
tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap
tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap
tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

as originally proposed in PR #135 by @friederbluemle

cleanup generated android/build.gradle artifact

---

package.json
yarn.lock

with eslint@6.4.0 update in devDependencies

eslint-plugin-node@10 update in devDependencies

---

README.md
lib/cli-command.js
tests/integration/cli/help/__snapshots__/cli-help.test.js.snap
tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap
tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap
tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap
tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap

according to the reality
and show that this is an `EXPERIMENTAL FEATURE NOT SUPPORTED`
as a quick fix solution
triggered by: #165, as raised by @yoshifumi4423
/cc @timojaask

Update description of `--use-cocoapods` option

---

templates/ios.js
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

✅ `npm test` ok
✅ example app tested on iOS

fix license in iOS podspec

---

README.md

doc: fix default React Native version in lib API

---

lib/cli-command.js
tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap
tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap

(and hide instructions for the example project if no example is generated)

show hint to generate example in CLI

---

lib/cli-program.js
package.json
tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap
tests/with-mocks/cli/program/with-defaults/for-android/cli-program-with-defaults-for-android.test.js
tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap
tests/with-mocks/cli/program/with-missing-args/cli-program-with-missing-args.test.js
yarn.lock

to enforce minimum Node.js version in CLI
got the idea from <https://github.com/prettier/prettier/pull/7837>

add package engines & use please-upgrade-node

---

lib/cli-command.js
lib/cli-program.js
package.json
tests/integration/cli/help/__snapshots__/cli-help.test.js.snap
tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap
tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap
tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/cli-command-with-bogus-platforms-name.test.js
tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/cli-command-with-empty-platforms-string.test.js
tests/with-mocks/cli/command/func/with-logging/with-error/cli-command-with-logging-with-error.test.js
tests/with-mocks/cli/command/func/with-options/cli-command-func-with-options.test.js
tests/with-mocks/cli/program/with-defaults/for-android/cli-program-with-defaults-for-android.test.js
yarn.lock

_Now tested in with generated example project_

quick commander@5 update

---

templates/ios.js
tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap
tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap
tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap
tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap
tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap
tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap
tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap
tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

add & update iOS podspec license comments

---

README.md
lib/cli-command.js

(issue #308 - issue with adding dependencies to the library root)
with other minor example log updates

log & document issue with example lib dependencies

---

.github/workflows/nodejs.yml
README.md
package.json
tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap
tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap

major: update minimum Node.js version to 10.20

---

lib/lib.js
tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap
tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap
tests/with-mocks/cli/command/action-func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

__updated:__
**example of log for native module, with no generated example:**
```
CREATE new React Native module with the following options:
name: awesomeModule
root moduleName
(full package name): react-native-awesome-module
is view: false
object class name prefix: SUPER
object class name: SUPERAwesomeModule
library modulePrefix: react-native
Android packageIdentifier: com.awesome
platforms: ios,android
Apple tvosEnabled: false
authorName: Your Name
authorEmail: yourname@email.com
author githubAccount: github_account
license: MIT
useAppleNetworking: false
CREATE: Generating the React Native library module
📚  Created library module react-native-awesome-module in `./react-native-awesome-module`.
🕘  It took 10ms.
====================================================
YOU'RE ALL SET!
💡 next …
```

update log of create parameters

---

README.md

- add badge from Stryker dashboard

update badges in README.md

---

templates/ios.js
tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap
tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap
tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap
tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap
tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap
tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap
tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap
tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

I discovered this while working on a version new SQLite plugin design for React Native, as discussed in <https://github.com/brodybits/ask-me-anything/issues/3>.
I think this should be in a new 0.x release.

fix iOS podspec for C sources

---

templates/ios.js
tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap
tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap
tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap
tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap
tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap
tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap
tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap
tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

for consistency with React Native 0.62-stable / 0.63-stable template
from facebook/react-native@8f93dedc / facebook/react-native#27922

add swift search paths to iOS pbxproj

---

README.md

- tvOS platform note
- outdated Node.js version requirement
- outdated view adaptation that was needed for Android

remove outdated info from README.md

---

package.json
tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap
tests/with-mocks/cli/program/with-example/with-logging/cli-program-with-example-with-logging.test.js
yarn.lock

The main purpose is to avoid surviving mutants in these lines: https://github.com/brodybits/create-react-native-module/blob/0.19.0/lib/cli-command.js#L18-L37

test mocked CLI program with example with log

---

.github/workflows/nodejs.yml
package.json
tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap
tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap
tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap

refactor!: update minimum Node.js version to 12

---

templates/ios.js
tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap
tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap
tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap
tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap
tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap
tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap
tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap
tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap
tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap
tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap
tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap
tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap
tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap
tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap
tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

(`cc`, `cpp`, `mm`)
in the generated podspec

feat: support more iOS source language extensions

---

lib/lib.js
tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap
tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap
tests/with-mocks/cli/command/action-func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap
tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap
tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap

also fixes minor misalignment that was introduced in 8bfc56124a9f8ff7c0b4e13f1f9ac95f684ed585 (PR #431)

refactor: nudge indenting of options in logging
