brodybits/create-react-native-module

templates/android.js, templates/general.js
- Android Gradle plugin 3.3.2 update as proposed in frostney/react-native-create-library#102
- Other generated Android build updates from React Native 0.59
- Update devDependencies for React Native 0.59.4
=> 0.5.0 updates

package.json, yarn.lock
done in 2 steps:
- use `yarn remove` command to remove the `eslint` items from `devDependencies`, in order to remove lingering `lodash` dependency from `yarn.lock` which had been causing some `yarn audit` warnings
- use `yarn add --dev` command to add the recent `eslint` dependency versions back to `devDependencies`, with updated `lodash` dependency in `yarn.lock`
Net result:
- updated `lodash` version in `yarn.lock`, which resolves the `yarn audit` warnings
- with no changes to `devDependencies` in `package.json`
verified as follows:
the following command:
git diff --name-only d2f88026..efa56633
only shows the following result:
yarn.lock
this result would also be visible in the [“Files changed” tab](https://github.com/brodybits/create-react-native-module/pull/36/files) of this PR. …
=> Release 0.6.0 yarn audit fix

templates/ios.js
Hey thanks for the development of this package!
I like to write my modules for swift, so after creating a new module with create-react-native-module I need to change the .podspec to include the swift files. 
If you think think this is a good idea, I would be happy if you can merge this PR!
=> Include .swift files in podspec

templates/example.js, templates/general.js, templates/ios.js, templates/windows.js
(not needed)
In case this kind of customization is needed in the future, it should be done in `templates/.eslintrc.yml` rather than in any of the JavaScript source files.
=> cleanup templates/*.js: remove zero max-len lines

templates/index.js
in templates/index.js
* add a line break
* do not overwrite object from another module in `Object.assign()` call, as such an overwrite is not needed and is not good form
Testing done:
* `npm test` (equivalent to `yarn test`) succeeds in my work area
* verified that the Travis CI build is green
Note that I think there is no need to do manual integration testing of the CLI, as the existing tests verify that changes to `templates/*.js` do not break anything.
Discovered while working on some cleanup related to evaluating use of my [`prettierx`](https://www.npmjs.com/package/prettierx) fork of Prettier (#5).
=> cleanup internal updatePlatformInFile function in templates/index.js

tests/helpers/io-mocks.js, tests/lib-example-config-options/__snapshots__/lib-example-config-options.test.js.snap, tests/lib-example-defaults/__snapshots__/lib-example-defaults.test.js.snap, tests/lib-view-with-example-config-options/__snapshots__/lib-view-with-example-config-options.test.js.snap, tests/lib-view-with-example-defaults/__snapshots__/lib-view-with-example-defaults.test.js.snap
* return more realistic `package.json` object for generated `example`, which fixes capture of the new `scripts` entry that is added to the example `package.json` object
* push more formal object entries to the I/O snapshot
* move the mock `jsonfile` definition directly below the mock `fs` definition, to make it easier to combine them in the future
=> jsonfile test updates & fixes

README.md, templates/general.js, tests/lib-android-config-options/__snapshots__/lib-android-config-options.test.js.snap, tests/lib-cli-command/lib-cli-command-func-android-ios-config-options/__snapshots__/lib-cli-command-func-android-ios-config-options.test.js.snap, tests/lib-defaults/__snapshots__/lib-defaults.test.js.snap, tests/lib-example-config-options/__snapshots__/lib-example-config-options.test.js.snap, tests/lib-example-defaults/__snapshots__/lib-example-defaults.test.js.snap, tests/lib-ios-config-options/__snapshots__/lib-ios-config-options.test.js.snap, tests/lib-view-android-config-options/__snapshots__/lib-view-android-config-options.test.js.snap, tests/lib-view-defaults/__snapshots__/lib-view-defaults.test.js.snap, tests/lib-view-ios-config-options/__snapshots__/lib-view-ios-config-options.test.js.snap, tests/lib-view-with-example-config-options/__snapshots__/lib-view-with-example-config-options.test.js.snap, tests/lib-view-with-example-defaults/__snapshots__/lib-view-with-example-defaults.test.js.snap, tests/lib-windows-config-options/__snapshots__/lib-windows-config-options.test.js.snap
and update README.md
resolves #42
Testing:
=> Drop support for React Native pre-0.59

.eslintrc.yml, bin/cli.js, lib/cli-program.js, package.json, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/help/cli-help.test.js, tests/mocked-lib-cli-program/cli-program-defaults-android/__snapshots__/cli-program-defaults-android.test.js.snap, tests/mocked-lib-cli-program/cli-program-defaults-android/cli-program-defaults-android.test.js, yarn.lock
* eslint updates
* jest@24.9.0 update
* uuid@3.3.3 update
* execa@2.0.4 update
* quick integration test of `./cli.js --help`
* Split up `cli.js`
* test `lib/cli-program.js` with mocking on Android
This update means that the code in `cli.js` is now covered by `yarn test` using Jest.
Testing done:
✅`yarn test` succeeds
✅able to create native package and run on iOS and Android
✅able to create native package with view and run on iOS and Android
=> 0.9.0 release updates

tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-example/with-options/create-with-example-with-options.test.js, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-name-in-camel-case/create-with-name-in-camel-case.test.js, tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap, tests/with-injection/create/with-options/for-ios/create-with-options-for-ios.test.js, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-array/platforms-array.test.js, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/create-with-custom-module-prefix.test.js, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-injection/create/with-options/with-module-name/create-with-module-name.test.js
that were not discovered by using Stryker (version 2.0.2):
* extra breaking mutation 1a: ignore `useCocoapods` in generateLibraryModule (see PR #81)
* extra breaking mutation 1b: ignore `useCocoapods` in generated example (see PR #82)
* extra breaking mutation 2: ignore `modulePrefix` in options object, which is the first term in an or (`||`) expression (see PR #83)
* extra breaking mutation 2a: ignore `prefix` in options object, which is the first term in an or (`||`) expression (see PR #84)
* extra breaking mutation 2.1: `moduleName = null` (ignore `moduleName` in options object), see PR #87;
* extra breaking mutation 3: use `name` value without paramCase call (see PR #86)
=> Add tests to cover extra breaking mutations

package.json, yarn.lock
✅`npm test` passes
✅Travis CI build is green
✅able to install from branch on GitHub, generate a simple native package with an example, and run the example on Android
installed from GitHub as follows:
npm i -g --verbose github:brodybits/create-react-native-module#commander-3-update
=> commander@3 update

templates/ios.js, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
See https://github.com/react-native-community/react-native-tvos/issues/8 for discussion :)
=> Adding tvOS support

README.md
that React Native 0.60 is currently not supported by Expo or react-native-windows
related to upcoming out-of-tree platform support to be documented, as followup to tvOS platform support (#95)
=> doc React Native 0.60 support quirk

templates/ios.js, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
For the sake of consistency
FUTURE TBD: I wonder if the minimum should be higher, since the iOS ecosystem seems to have moved beyond older iOS versions such as iOS 9 and iOS 10.
P.S. This update was made in response to my review and examination of PR #91 (added tvOS support).
=> Update minimum iOS version to 9.0

lib/cli-command.js, lib/lib.js, tests/with-injection/create/with-defaults/bogus-platforms/bogus-name/__snapshots__/bogus-platforms-name.test.js.snap, tests/with-injection/create/with-defaults/bogus-platforms/bogus-name/bogus-platforms-name.test.js, tests/with-injection/create/with-defaults/bogus-platforms/empty-array/__snapshots__/bogus-platforms-empty-array.test.js.snap, tests/with-injection/create/with-defaults/bogus-platforms/empty-array/bogus-platforms-empty-array.test.js, tests/with-injection/create/with-defaults/bogus-platforms/empty-string/__snapshots__/bogus-platforms-empty-string.test.js.snap, tests/with-injection/create/with-defaults/bogus-platforms/empty-string/bogus-platforms-empty-string.test.js, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/create-with-example-with-null-prefix.test.js, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/cli-command-with-bogus-platforms-name.test.js, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/cli-command-with-empty-platforms-string.test.js, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/create-with-example-with-options.test.js, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/create-with-example-with-options.test.js
* no normalization of platforms in `lib/cli-command.js` (as this step is not needed)
* do not use defaults for normalized options in `lib/lib.js` (and rename the internal function involved)
* additional testing of related options
Stryker Mutator shows 100% coverage in `lib/lib.js` with this proposed update.
General motivation: it is desired to achieve as much coverage as possible before refactoring lib.js to remove asynchronous system I/O calls.
=> normalized options cleanup with some additional testing

lib/cli-program.js, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/integration/cli/noargs/cli-noargs.test.js
Fix #48 .
Root cause: The `commander` module seems to try to detect this problem and push the `--help` argument on `process.argv`.  Unfortunately, that push is silently ignored, leading to the ugly error message issue.
Fix: Create our own args array, detect this condition, push `--help` onto the arg array, and then proceed with `program.parse()`.
Snapshot test also added.
=> Fix crash when no args passed in

tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap, tests/with-mocks/cli/program/with-missing-args/cli-program-with-missing-args.test.js
as a followup to PR #109 ..
rationale: I like to cover as much as possible by unit testing
Primary purpose of the spawned integration tests is to cover anything that cannot be covered by in-process unit testing.
I would like to merge this proposal within the next 12-24 hours, before making the next patch release.
/cc @dlowder-salesforce
=> unit test of missing CLI args using mocks

package.json, yarn.lock
Looking through the changes to `yarn.lock`, this update seems to completely remove some older indirect dependencies such as @babel/generator@7.4.4, @babel/traverse@7.4.5, and fs-extra@7.0.1.
If I would revert the test updates since 0.9.2 and do `yarn jest -u`, Stryker continues to show 100% coverage in `lib/lib.js` and `lib/normalized-options.js`. This means that Stryker seems to still miss the extra breaking mutations that I raised in #89 & PR #103.
/cc @dlowder-salesforce @dsyne
=> Stryker Mutator 2.1.0 tool updates

.gitignore, package.json, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/view/cli-create-with-view.test.js, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/integration/cli/create/with-defaults/cli-create-with-defaults.test.js, yarn.lock
_with and without the `--view` option_
using `recursive-readdir` _(with additional sorting of the file path list)_ & `fs.readFileSync()` to _read and check_ the contents of the generated library module artifacts
with the generated test artifacts ignored as specified by added `.gitignore` entries (this is a departure from a common approach of running this kind of test in a temporary directory, using a utility package such as `tmp` or perhaps `temp-dir`)
/cc @dlowder-salesforce @dsyne
=> CLI create integration testing

templates/.eslintrc.yml, templates/android.js
(minor fixes in templates/android.js)
removes an exception from `templates/.eslintrc.yml`
=> no-useless-escape rule fix in templates

templates/android.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
This wraps the `buildscripts` section in the generated `build.gradle` file in a conditional, avoiding unnecessary downloads of/conflicts with different Android Gradle plugin distributions in application projects.
Please check https://github.com/facebook/react-native/pull/25569 for a related discussion, specifically this comment: https://github.com/facebook/react-native/pull/25569#issuecomment-532504277
The commit also includes some minor indentation fixes in the same file.
Closes #129
<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the …
=> Update android build.gradle template setup

README.md
due to known issues with react-native-tvos@0.59
and update the level of testing in the documentation
in response to review of PR #126
=> document minimum react-native-tvos version

tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/cli-command-with-bogus-platforms-name.test.js, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/cli-command-with-empty-platforms-string.test.js
for tests with bogus values of `platforms`
* use internal 1ms timer to give CLI func output time to finish & update the affected snapshots
* use a string replace WORKAROUND HACK to work around indeterminate elapsed time in the log
* test updates for Windows
These tests now cover *most* of the CLI function log output.
=> CLI command function test fixes

tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/cli-command-with-bogus-platforms-name.test.js, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/cli-command-with-empty-platforms-string.test.js
simply do `await func(...)` rather than waiting for a 1ms timer
=> fix async CLI func tests again

tests/with-mocks/cli/command/func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-error/cli-command-with-logging-with-error.test.js
for coverage of some error logging code in `lib/cli-command.js`
This test case comes from test updates originally proposed in PR #102, with an extra workaround hack due to non-deterministic elapsed time.
=> test CLI command func error with logging

stryker.conf.js
Seems to add about 50% to the mutation testing time, should not be an issue on modern systems.
Does not seem to find any more mutants in `templates` at this point.
=> update stryker.conf.js to include templates

README.md
Document tvOS as a platform fork and not an "out of tree platform", with all of the points in a special bullet list.
This is to update the documentation of the actual status before merging PR #126 to make tvOS platform support optional.
/cc @dlowder-salesforce
=> doc fixes for tvOS platform fork (quick fixes)

README.md, lib/cli-command.js, lib/lib.js, templates/example.js, templates/ios.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-example/with-options/create-with-example-with-options.test.js, tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap, tests/with-injection/create/with-options/for-ios/create-with-options-for-ios.test.js, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
__replace `--use-cocoapods` with `--use-apple-networking` & `--write-example-podfile`__
* _extra example ios/Podfile is now behind its own *experimental* option flag, with a couple of trailing tabs removed_
* update the final CLI log message to *always* include instructions to do `pod install`, with a comment depending on use of `--write-example-podfile` or not
* with an outdated DEFAULT constant removed, as it is not really needed
* with CLI error logging test snapshot updated (due to the effect of the change on the stack trace)
This proposal should be considered a BREAKING CHANGE, for a 0.x minor release as opposed to a patch release.
This is a followup to PR #166 (update description to match the reality), in response to issue #155.
Resolves #145 (rename `--use-cocoapods` option).
TODO …
=> [BREAKING] replace --use-cocoapods with 2 options

templates/android.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
near to the beginning of `android/build.gradle`
(using single quotes in definition of `DEFAULT_BUILD_TOOLS_VERSION`)
and remove some comments that are not needed
as a followup to PR #135
verified that:
* ✅ `npm t` (`npm test`) passes
* ✅ able to generate view module with example that works with React Native 0.59
* ✅ able to generate non-view module with example that works with React Native 0.59
* ✅ able to generate non-view module with example that works with React Native 0.60
* ✅ able to generate non-view module with example that works with React Native 0.61-rc
* ✅ Travis CI build is green
The one potential drawback is that this update continues with a minor divergence from the React Native template.
/cc @friederbluemle
=> move constants in generated android/build.gradle

templates/android.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
Resolves #120 
`javaCompile` was deprecated in the Android Gradle plugin as of v3.3.0 in favor of `javaCompileProvider` to support lazy task configuration (see [release notes](https://developer.android.com/studio/releases/gradle-plugin)). 
Since the Android Gradle plugin is [currently configured in the template to v3.4.1](https://github.com/brodybits/create-react-native-module/blob/master/templates/android.js#L38) it's safe to just use `javaCompileProvider` directly.
=> Issues/120: Use javaCompileProvider in Android template

package.json, yarn.lock
At this point Stryker 2.5.0 seems to find 3 more surviving code mutants than 2.1.0. Here are the surviving mutants discovered at this point:
```
5. [Survived] StringLiteral
/home/brodybits/create-react-native-module/lib/cli-command.js:16:38
-   pod install # ${writeExamplePodfile ? `required` : `required starting with React Native 0.60`}
+   pod install # ${writeExamplePodfile ? "" : `required starting with React Native 0.60`}
Ran all tests for this mutant.
18. [Survived] ArithmeticOperator
/home/brodybits/create-react-native-module/lib/cli-command.js:47:34
-   ${emoji.get('clock9')}  It took ${Date.now() - beforeCreation}ms.
+   ${emoji.get('clock9')}  It took ${Date.now() + beforeCreation}ms.
Ran all tests for this mutant.
20. [Survived] ConditionalExpression …
```
=> [dev] @stryker-mutator 2.5.0 updates

lib/lib.js, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap, tests/with-mocks/cli/command/func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
(and add a little extra spacing in the process)
Rationale: a higher-level interactive utility such as [`brodybits/react-native-module-init`](https://github.com/brodybits/react-native-module-init) may want to offer its own way to add a generated example.
This update removes some unwanted log output from [`brodybits/react-native-module-init`](https://github.com/brodybits/react-native-module-init) discussed in:
- <https://github.com/brodybits/react-native-module-init/issues/9>
- proposed update in <https://github.com/brodybits/react-native-module-init/pull/8>
=> no log of generated example options unless enabled

lib/cli-command.js, package.json, yarn.lock
with some symbols from `log-symbols`
based on logs from this interactive CLI tool:
- https://github.com/brodybits/react-native-module-init
Some final output from testing in my workarea:
```
💡 check out the example app in react-native-awesome-module/example
💡 recommended: run Metro Bundler in a new shell
ℹ (cd react-native-awesome-module/example && yarn start)
💡 enter the following commands to run the example app:
ℹ cd react-native-awesome-module/example
ℹ react-native run-ios
ℹ react-native run-android
⚠ first steps in case of a clean checkout
ℹ run Yarn in react-native-awesome-module/example/ios
ℹ (cd react-native-awesome-module/example && yarn)
ℹ do `pod install` for iOS in react-native-awesome-module/example/ios
ℹ cd react-native-awesome-module/example
ℹ (cd ios && pod install)
```
=> log more example app info in the end

lib/lib.js, templates/windows.js, tests/with-mocks/cli/command/func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap
(templates/windows.js)
rationale: it is desired to move templates/windows.js into
an "unsupported" directory tree, and then test it using
uuid from devDependencies, in the near future
✅ `npm test` is ok
=> refactoring: move require('uuid') out of templates

package.json, stryker.conf.js
- renamed `stryker` scripts entry in `package.json`
- split `mutate` configuration into multiple lines in `stryker.conf.js`
- split `reporters` configuration into multiple lines in `stryker.conf.js`
- TBD commented out for now: add `bin/**/*.js` to mutate configuration in `stryker.conf.js` (there seems to be an issue to be investigated with Stryker mutation testing on `bin/*.js`)
✅ `npm test` ok
✅ `yarn stryker` command starts running Stryker mutation testing which shows the limited number of surviving mutants in the end and generates the HTML report as enabled by the configuration
=> updates to setup of Stryker Mutator

lib/lib.js, lib/normalized-options.js, tests/with-mocks/cli/command/func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap
followup to 0de40fa - remove Windows (C#) support (PR #264)
extra namespace parameter no longer needed was discovered through
mutation testing using Stryker Mutator (as reported in issue #274)
namespace parameter is commented out for now, at least
(with an error logging test snapshot updated and a couple of other cleanup changes)
removed from library API since Windows platform is no longer supported
Note that it should be possible to add Windows platform again with support for the namespace parameter at some point in the future.
=> remove library API support for namespace

README.md, lib/cli-command.js, lib/normalized-options.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap
__Updated:__
- export & document `--class-name` CLI option
- document className library API option
- update description of `prefix` option
- fix & update description of modulePrefix
- remove an "option NOT DOCUMENTED & NOT SUPPORTED" comment
- update test snapshots
Undocumented `className` option was discovered in `lib/normalized-options.js` during cleanup removal of obsolete `namespace` option in PR #276 (followup fix to PR #264 to remove Windows (C#) support)
__Testing:__
P.S. Update needed to description of modulePrefix was discovered while working on the undocumented `className` option.
=> fix --class-name & some other options

.github/workflows/pr-merge.yml
https://github.com/marketplace/actions/pull-request-merge-command
to pull & test from master before merging a PR
General motivation:
- ~~It is safest to pull and test from master before merging a PR~~ _GitHub should test this automatically, doesn't hurt to pull from master before merging though._
- There are PRs such as #277 which I may want to keep testing from the GitHub UI before I am finally ready to merge.
---
I did test this action on my own scratch project, hope it will work as expected on this one.
=> add PR merge action

README.md, lib/cli-command.js, lib/normalized-options.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap
This reverts commit 7c729902e3c6109179f9180aa5ff473fcb5e6324.
It is desired to use a different name such as --object-name or
--native-object-name rather than --class-name.
The next step is to revisit the changes to the descriptions of
the --prefix & --module-prefix options.
=> Revert "fix --class-name & some other options (#278)"

README.md, lib/cli-command.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap
- fix description of the mandatory `name` parameter in the library API
- update `--prefix` & `--module-prefix` descriptions in `README.md`
- update `--prefix` & `--module-prefix` descriptions in `cli-command.js`
- update test snapshots
followup to reverted PR #278 (reverted in #299) which was in followup to PRs #276 & #264 (removing Windows C# platform support)
I think this series of updates and fixes shows the benefit of slower and more careful development.
=> fix API & option descriptions

lib/cli-command.js, tests/with-injection/cli/command/action-error/cli-action-error-empty-args-missing-name.test.js, tests/with-injection/cli/command/action-error/cli-action-error-too-many-args.test.js, tests/with-injection/cli/command/action-error/cli-action-error-undefined-args-missing-name.test.js
- throw explicit error in case of missing `args` or empty `args` array from `lib/cli-program.js` - resolves #305
- throw error in case of too many arguments in `args` array from `lib/cli-program.js` - resolves #119
with CLI lib tests in `tests/with-injection/cli/command/action-error`
---
P.S. This was tested from the command line with the following commands:
- `./bin/cli.js --view`
- `./bin/cli.js name1 name2`
=> quick fixes to handle CLI args errors

.github/workflows/stryker.yml, stryker.conf.js
P.S. The prerequisite is to configure the Stryker dashboard API key ref:
- https://stryker-mutator.io/blog/2019-12-27/stryker-dashboard-host-your-mutation-testing-report
- https://github.com/stryker-mutator/stryker-handbook/blob/master/dashboard.md
- https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
=> add Stryker GitHub action

README.md, lib/cli-command.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap
- move --module-name & --view options to near the beginning in CLI & documentation
- update help text & documentation of --module-name, --view, & --module-prefix options
- document className option in library API
(which is deprecated due to plans to rename the option)
- update documentation of prefix option in library API only
=> update create options

README.md, lib/cli-command.js, lib/lib.js, lib/normalized-options.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-example/with-options/create-with-example-with-options.test.js, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap
- update a test to test with object class name library API option ref: issue #336
- rename `className` to `objectClassName` in library API & update test case - BREAKING CHANGE
- add `--object-class-name` CLI option for `objectClassName`
- deprecate `prefix` option in CLI help test & documentation, which could be problematic due to issue #337
- documentation updates
- update affected test snapshots
intended for upcoming 0.x release
TODO items __- done__:
=> major: object class name updates

lib/lib.js, templates/android.js, templates/example.js, templates/general.js, templates/ios.js
- use objectClassName instead of name in `templates/*.js`, in followup to object class name updates in 761123b6 / PR #338
- remove `name: objectClassName` template args no longer needed in `lib/lib.js`
(this cleanup should really have been part of PR #338)
=> cleanup object class name references

tests/unsupported-platforms/windows-csharp/with-defaults/windows-csharp-with-defaults.test.js, tests/unsupported-platforms/windows-csharp/with-options/windows-csharp-with-options.test.js, unsupported-platforms/windows-csharp.js
- export objectClassName in unsupported-platforms/windows-csharp.js
(export objectClassName prop rather than non-descriptive name prop)
(in followup to objectClassName update in 761123b6 / PR #338)
- use `objectClassName` prop in windows-csharp platform tests
(unsupported windows-csharp platform tests)
=> export objectClassName prop in windows template

templates/ios.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
- fix indenting of `"$(inherited)",` line in generated iOS pbxproj
- update affected test snapshots
discovered when using Xcode to add some dependencies for iOS while working on new SQLite plugin design for React Native, as discussed in <https://github.com/brodybits/ask-me-anything/issues/3>
In short, Xcode actually fixed this indentation issue when I added some other dependencies. I think it would be better to get this right the first time in the generated pbxproj.
TODO:
=> fix minor indenting issue in ios pbxproj

templates/ios.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-ios/__snapshots__/create-view-with-options-for-ios.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-ios/__snapshots__/create-with-options-for-ios.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
- remove Objective-C module sources from generated iOS pbxproj
- update affected test snapshots
Rationale: Objective-C module sources are not needed in the iOS pbxproj, now that they are picked up by the podfile.
should target new 0.x release
__Testing:__
=> remove sources from generated iOS pbxproj

templates/ios.js, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
tested on:
- React Native 0.62
- react-native-tvos 0.62
- React Native 0.61
- React Native0.60
=> remove extra blank line from generated iOS module

lib/cli-command.js, lib/lib.js, package.json, tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/bogus-name/cli-command-with-bogus-platforms-name.test.js, tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/empty-string/cli-command-with-empty-platforms-string.test.js, tests/with-mocks/cli/command/action-func/with-logging/with-error/cli-command-with-logging-with-error.test.js, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/create-with-example-with-defaults.test.js, tests/with-mocks/lib/create/with-example/with-logging/with-error/with-yarn-error-logging.test.js, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/create-with-example-with-options.test.js, tests/with-mocks/lib/create/with-example/with-logging/with-options/create-with-example-with-options.test.js, yarn.lock
motivation:
- avoid need for hackish `global.console` mocking in some tests
- make it much easier to add test coverage to avoid surviving mutants in these lines: https://github.com/brodybits/create-react-native-module/blob/0.19.0/lib/cli-command.js#L18-L37
=> add & use console package

templates/android.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/for-android-only/__snapshots__/create-with-example-for-android-only.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
seems to be not needed and now deprecated ref:
- https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
BREAKING CHANGE
=> refactor!: remove JCenter support

templates/android.js, tests/integration/cli/create/view/__snapshots__/cli-create-with-view.test.js.snap, tests/integration/cli/create/with-defaults/__snapshots__/cli-create-with-defaults.test.js.snap, tests/with-injection/create/view/with-defaults/__snapshots__/create-view-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/view/with-options/for-android/__snapshots__/lib-view-android-config-options.test.js.snap, tests/with-injection/create/with-defaults/__snapshots__/create-with-defaults.test.js.snap, tests/with-injection/create/with-example/for-android-only/__snapshots__/create-with-example-for-android-only.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-missing-package-scripts/__snapshots__/recover-from-missing-package-scripts.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-injection/create/with-example/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-injection/create/with-name-in-camel-case/__snapshots__/create-with-name-in-camel-case.test.js.snap, tests/with-injection/create/with-options/for-android/__snapshots__/create-with-options-for-android.test.js.snap, tests/with-injection/create/with-options/platforms-array/__snapshots__/platforms-array.test.js.snap, tests/with-injection/create/with-options/platforms-comma-separated/__snapshots__/platforms-comma-separated.test.js.snap, tests/with-injection/create/with-options/with-custom-module-prefix/__snapshots__/create-with-custom-module-prefix.test.js.snap, tests/with-injection/create/with-options/with-module-name/__snapshots__/create-with-module-name.test.js.snap, tests/with-mocks/cli/command/action-func/with-options/__snapshots__/cli-command-func-with-options.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap
(generated build.gradle)
Discovered while looking to remove some `build.gradle` entries not needed by all users
related to:
- PR #143 - followup to android build.gradle template setup updates
- PR #135 - Update android build.gradle template setup
=> fix(cleanup): remove extra plugin items from build.gradle

templates/example.js, tests/with-injection/create/view/with-example/with-defaults/__snapshots__/create-view-with-example-with-defaults.test.js.snap, tests/with-injection/create/view/with-example/with-options/__snapshots__/create-view-with-example-with-options.test.js.snap, tests/with-injection/create/with-example/for-android-only/__snapshots__/create-with-example-for-android-only.test.js.snap, tests/with-injection/create/with-example/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-injection/create/with-example/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-null-prefix.test.js.snap, tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap
similar to: https://github.com/brodybits/react-native-module-init/pull/66
as suggested in: https://github.com/brodybits/create-react-native-module/issues/232#issuecomment-653447868
=> fix: resolve absolute paths in example metro watch folders

README.md
__(updated)__
for upcoming 0.20.0 release (see issue #409)
* React Native pre-0.63 support is now deprecated (see issue #423)
* known issue with React Native 0.64 (rc) on iOS (see issue #422)
* add link to @otobank fork (see #425)
* document --use-apple-networking as EXPERIMENTAL & NOT SUPPORTED
(see issue #426)
=> doc: apply general documentation updates - February 2021

README.md, lib/cli-command.js, lib/lib.js, lib/normalized-options.js, templates/android.js, templates/example.js, templates/general.js, templates/ios.js, tests/integration/cli/help/__snapshots__/cli-help.test.js.snap, tests/integration/cli/noargs/__snapshots__/cli-noargs.test.js.snap, tests/with-injection/cli/command/object/__snapshots__/lib-cli-command-object-text.test.js.snap, tests/with-injection/create/view/with-example/with-options/create-view-with-example-with-options.test.js, tests/with-injection/create/with-example/with-options/create-with-example-with-options.test.js, tests/with-injection/create/with-options/for-android/create-with-options-for-android.test.js, tests/with-injection/create/with-options/with-package-name/__snapshots__/create-with-package-name.test.js.snap, tests/with-injection/create/with-options/with-package-name/create-with-package-name.test.js, tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/bogus-name/__snapshots__/cli-command-with-bogus-platforms-name.test.js.snap, tests/with-mocks/cli/command/action-func/with-logging/with-bogus-platforms/empty-string/__snapshots__/cli-command-with-empty-platforms-string.test.js.snap, tests/with-mocks/cli/command/action-func/with-logging/with-error/__snapshots__/cli-command-with-logging-with-error.test.js.snap, tests/with-mocks/cli/program/with-defaults/for-android/__snapshots__/cli-program-with-defaults-for-android.test.js.snap, tests/with-mocks/cli/program/with-example/with-logging/__snapshots__/cli-program-with-example-with-logging.test.js.snap, tests/with-mocks/cli/program/with-missing-args/__snapshots__/cli-program-with-missing-args.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-defaults/__snapshots__/create-with-example-with-defaults.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-error/__snapshots__/with-yarn-error-logging.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-null-options/with-null-prefix/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/__snapshots__/create-with-example-with-options.test.js.snap, tests/with-mocks/lib/create/with-example/with-logging/with-options/create-with-example-with-options.test.js
(part of release `0.2.0` as discussed in #409)
- rename `--module-name` option to `--package-name`
- rename `--package-identifier` option to '--native-package-id`
- rename `--example-react-native-version` to `--example-react-native-template`
- update description & help text of the affected options
- add a space to indenting of options in logging
BREAKING CHANGE: affects anyone using the renamed options
=> refactor!: rename some options

README.md
as discussed in: https://github.com/brodybits/create-react-native-module/issues/43#issuecomment-891320527
/cc @asklar
=> docs: add pointer for Windows target platform
